[versions]
android-minSdk = "23"
android-targetSdk = "36"

android = "8.13.0" # https://kotlinlang.org/docs/multiplatform-compatibility-guide.html#version-compatibility
kotlin = "2.3.0"
maven-publish = "0.36.0"

activity-compose = "1.12.3"
androidx-compose-bom = "2026.01.01"
jetbrains-compose = "1.10.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "android" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "android" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }

jetbrains-compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "jetbrains-compose" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
