[versions]
android-minSdk = "23"
android-targetSdk = "36"

android = "9.0.1" # https://kotlinlang.org/docs/multiplatform-compatibility-guide.html#version-compatibility
kotlin = "2.3.10"
maven-publish = "0.36.0"

activity-compose = "1.12.4"
androidx-compose-bom = "2026.02.00"
jetbrains-compose = "1.10.1"
kermit = "2.0.8"

[plugins]
android-application = { id = "com.android.application", version.ref = "android" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "android" }

kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }

jetbrains-compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "jetbrains-compose" }

kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
